databases:
  - name: connectlaundry-db
    plan: free
    databaseName: connectlaundry_db
    user: connect_admin

services:
  - type: web
    name: connect-laundry-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: connectlaundry-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: REDIS_URL
        value: ""
      - key: DJANGO_LOG_LEVEL
        value: INFO
